networks:
  public:
    driver: bridge

services:
  runner:
    container_name: runner
    image: runner_agent:latest
#    build:
#      dockerfile: ./race.Dockerfile
    networks:
      - public
    volumes:
      - .env:/home/app/.env
